/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ErBit.java
 *
 * Created on 2011-sep-30, 20:41:29
 */
package gui;

import chrriis.common.UIUtils;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import gui.Receive;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import java.io.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.net.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultTreeCellRenderer;

/**
 * 
 * @author Deno
 */
public class ErBit extends javax.swing.JFrame {

	Receive receive;

	// MyBrowser wb;

	/** Creates new form ErBit */
	public ErBit() {
		initComponents();
		setExtras();
		setVisible(true);
		fileDrop();
		// wb = new MyBrowser();
		// wb.start();
		receive = new Receive();
		receiveMessages();
	}

	private void setExtras() {
		Toolkit toolkit = Toolkit.getDefaultToolkit();
		Dimension dim = toolkit.getScreenSize();
		int x = (dim.width - super.getWidth()) / 2;
		int y = (dim.height - super.getHeight()) / 2;
		super.setLocation(x, y);
		super.setIconImage(toolkit.getImage(getClass().getResource(
				"/gui/img/icon.png")));
		JfileFrame.setIconImage(toolkit.getImage(getClass().getResource(
				"/gui/img/icon.png")));
		JfileFrame2.setIconImage(toolkit.getImage(getClass().getResource(
				"/gui/img/icon.png")));
		preferenceFrame.setIconImage(toolkit.getImage(getClass().getResource(
				"/gui/img/icon.png")));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		preferenceFrame = new javax.swing.JFrame();
		jPanel6 = new javax.swing.JPanel();
		jScrollPane6 = new javax.swing.JScrollPane();
		jTree2 = new javax.swing.JTree();
		jPanel7 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel10 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jPanel11 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jPanel8 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jPanel12 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jPanel13 = new javax.swing.JPanel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jTextField1 = new javax.swing.JTextField();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jToolBar1 = new javax.swing.JToolBar();
		jSeparator3 = new javax.swing.JToolBar.Separator();
		jButton1 = new javax.swing.JButton();
		jSeparator4 = new javax.swing.JToolBar.Separator();
		jButton5 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JToolBar.Separator();
		jButton4 = new javax.swing.JButton();
		jSeparator2 = new javax.swing.JToolBar.Separator();
		jPanel2 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTable3 = new javax.swing.JTable();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTable4 = new javax.swing.JTable();
		jPanel3 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();
		jPanel9 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem9 = new javax.swing.JMenuItem();
		jSeparator5 = new javax.swing.JPopupMenu.Separator();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenuItem7 = new javax.swing.JMenuItem();
		jMenuItem8 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();

		jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		DefaultTreeCellRenderer renderer2 = (DefaultTreeCellRenderer) jTree2
				.getCellRenderer();
		renderer2.setClosedIcon(new javax.swing.ImageIcon(getClass()
				.getResource("")));
		renderer2.setOpenIcon(new javax.swing.ImageIcon(getClass().getResource(
				"")));
		javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode(
				"Preference");
		javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode(
				"General");
		treeNode1.add(treeNode2);
		treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("UI Settings");
		treeNode1.add(treeNode2);
		treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Directories");
		treeNode1.add(treeNode2);
		jTree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
		jTree2.setSelectionPath(jTree2.getPathForRow(0));
		jTree2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTree2MousePressed(evt);
			}
		});
		jScrollPane6.setViewportView(jTree2);

		jPanel6.add(jScrollPane6,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1,
						365));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
		jLabel1.setText("General");
		jLabel1.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		jPanel10.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Listening Port"));

		jLabel4.setText("Port:");

		jTextField2.setText(Integer.toString(port));

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(
				jPanel10);
		jPanel10.setLayout(jPanel10Layout);
		jPanel10Layout
				.setHorizontalGroup(jPanel10Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel10Layout
										.createSequentialGroup()
										.addComponent(jLabel4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jTextField2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												51,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(253, Short.MAX_VALUE)));
		jPanel10Layout
				.setVerticalGroup(jPanel10Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel10Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel10Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(30, Short.MAX_VALUE)));

		jPanel11.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Number of Connections"));

		jLabel5.setText("Maximum number of peers:");

		jLabel6.setText("Maximum number of peers per torrents:");

		jTextField3.setText(Integer.toString(globalNumWant));

		jTextField4.setText(Integer.toString(numWant));

		javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(
				jPanel11);
		jPanel11.setLayout(jPanel11Layout);
		jPanel11Layout
				.setHorizontalGroup(jPanel11Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel11Layout
										.createSequentialGroup()
										.addGroup(
												jPanel11Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel6)
														.addComponent(jLabel5))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												95, Short.MAX_VALUE)
										.addGroup(
												jPanel11Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jTextField3)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																52,
																Short.MAX_VALUE))));
		jPanel11Layout
				.setVerticalGroup(jPanel11Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel11Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel11Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel11Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(21, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout
				.setHorizontalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanel11,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanel10,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																350,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jPanel10,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel11,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(67, Short.MAX_VALUE)));

		jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				129, 11, 370, 310));

		jPanel8.setVisible(false);

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));
		jLabel2.setText("UI Settings");
		jLabel2.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
				jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel8Layout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel2,
								javax.swing.GroupLayout.DEFAULT_SIZE, 350,
								Short.MAX_VALUE).addContainerGap()));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel8Layout.createSequentialGroup().addComponent(jLabel2)
						.addContainerGap(277, Short.MAX_VALUE)));

		jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				129, 11, 370, 310));

		jPanel12.setVisible(false);

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24));
		jLabel3.setText("Directories");
		jLabel3.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		jPanel13.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Location of Downloaded Files"));

		jCheckBox1.setSelected(true);
		jCheckBox1.setText("Default");
		jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jCheckBox1MousePressed(evt);
			}
		});

		OperatingSystem os = new OperatingSystem();
		if (OperatingSystem.windows()) {
			directoryPath = directoryPath + "\\Downloads";
		} else {
			directoryPath = directoryPath + "/Downloads";
		}
		checkDirectory(directoryPath);

		// if(os.windows()){
		// jTextField1.setText(directoryPath);
		// }else if(os.mac()){
		// jTextField1.setText(directoryPath);
		// }else if(os.unix()){
		// jTextField1.setText(directoryPath);
		// }
		jTextField1.setEditable(false);
		jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextField1KeyPressed(evt);
			}
		});

		jButton6.setText("jButton6");
		jButton6.setEnabled(false);
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(
				jPanel13);
		jPanel13.setLayout(jPanel13Layout);
		jPanel13Layout
				.setHorizontalGroup(jPanel13Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel13Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel13Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel13Layout
																		.createSequentialGroup()
																		.addGap(21,
																				21,
																				21)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				263,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				23,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jCheckBox1))
										.addContainerGap(19, Short.MAX_VALUE)));
		jPanel13Layout
				.setVerticalGroup(jPanel13Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel13Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jCheckBox1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel13Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton6))
										.addContainerGap(51, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(
				jPanel12);
		jPanel12.setLayout(jPanel12Layout);
		jPanel12Layout
				.setHorizontalGroup(jPanel12Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel12Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel12Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel13,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																350,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel12Layout.setVerticalGroup(jPanel12Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel12Layout
						.createSequentialGroup()
						.addComponent(jLabel3)
						.addGap(18, 18, 18)
						.addComponent(jPanel13,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(126, 126, 126)));

		jPanel6.add(jPanel12,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 11, 370,
						310));

		jButton7.setText("Apply");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		jPanel6.add(jButton7,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 353, -1,
						-1));

		jButton8.setText("Cancel");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});
		jPanel6.add(jButton8,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 353, -1,
						-1));

		jButton9.setText("Ok");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});
		jPanel6.add(jButton9,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 353, -1,
						-1));

		javax.swing.GroupLayout preferenceFrameLayout = new javax.swing.GroupLayout(
				preferenceFrame.getContentPane());
		preferenceFrame.getContentPane().setLayout(preferenceFrameLayout);
		preferenceFrameLayout.setHorizontalGroup(preferenceFrameLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel6,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		preferenceFrameLayout.setVerticalGroup(preferenceFrameLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel6,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("ErBit");

		jPanel1.setBackground(new java.awt.Color(0, 0, 0));

		jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
		jToolBar1.setFloatable(false);
		jToolBar1.setRollover(true);
		jToolBar1.add(jSeparator3);

		jButton1.setBackground(new java.awt.Color(0, 0, 0));
		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/gui/img/add torrent.png"))); // NOI18N
		jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton1.setToolTipText("Add torrent");
		jButton1.setFocusable(false);
		jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton1);
		jToolBar1.add(jSeparator4);

		jButton5.setBackground(new java.awt.Color(0, 0, 0));
		jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/gui/img/start.png"))); // NOI18N
		jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton5.setToolTipText("Start torrent");
		jButton5.setFocusable(false);
		jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton5);

		jButton2.setBackground(new java.awt.Color(0, 0, 0));
		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/gui/img/pause.png"))); // NOI18N
		jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton2.setToolTipText("Pause torrent");
		jButton2.setFocusable(false);
		jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton2);

		jButton3.setBackground(new java.awt.Color(0, 0, 0));
		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/gui/img/stop.png"))); // NOI18N
		jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton3.setToolTipText("Stop torrent");
		jButton3.setFocusable(false);
		jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton3);
		jToolBar1.add(jSeparator1);

		jButton4.setBackground(new java.awt.Color(0, 0, 0));
		jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/gui/img/remove.png"))); // NOI18N
		jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton4.setToolTipText("Remove torrent");
		jButton4.setFocusable(false);
		jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton4);
		jToolBar1.add(jSeparator2);

		jPanel2.setBackground(new java.awt.Color(0, 0, 0));
		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));

		jTable2.setBackground(new java.awt.Color(240, 240, 240));
		jTable2.setModel(model2);
		jTable2.setGridColor(new java.awt.Color(240, 240, 240));
		jTable2.setSelectionBackground(new java.awt.Color(0, 0, 0));
		jTable2.setSelectionForeground(new java.awt.Color(240, 240, 240));
		jScrollPane3.setViewportView(jTable2);

		jTabbedPane1.addTab("Peers", jScrollPane3);

		jTable3.setBackground(new java.awt.Color(240, 240, 240));
		jTable3.setModel(model3);
		jTable3.setGridColor(new java.awt.Color(240, 240, 240));
		jTable3.setSelectionBackground(new java.awt.Color(0, 0, 0));
		jTable3.setSelectionForeground(new java.awt.Color(240, 240, 240));
		jScrollPane4.setViewportView(jTable3);

		jTabbedPane1.addTab("Trackers", jScrollPane4);

		jTable4.setBackground(new java.awt.Color(240, 240, 240));
		jTable4.setModel(model4);
		jTable4.setGridColor(new java.awt.Color(240, 240, 240));
		jTable4.setSelectionBackground(new java.awt.Color(0, 0, 0));
		jTable4.setSelectionForeground(new java.awt.Color(240, 240, 240));
		jScrollPane5.setViewportView(jTable4);

		jTabbedPane1.addTab("Files", jScrollPane5);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 863,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel2Layout
						.createSequentialGroup()
						.addContainerGap(23, Short.MAX_VALUE)
						.addComponent(jTabbedPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 148,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		jPanel3.setBackground(new java.awt.Color(0, 0, 0));

		jPanel5.setPreferredSize(new java.awt.Dimension(147, 245));

		treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Torrents");
		treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Downloading");
		treeNode1.add(treeNode2);
		treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Uploading");
		treeNode1.add(treeNode2);
		treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Finished");
		treeNode1.add(treeNode2);
		jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
		jTree1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jTree1.setCellRenderer(new MyRenderer());
		DefaultTreeCellRenderer renderer = (DefaultTreeCellRenderer) jTree1
				.getCellRenderer();
		renderer.setClosedIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/gui/img/downNup.png")));
		renderer.setOpenIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/gui/img/downNup.png")));
		jTree1.setSelectionPath(jTree1.getPathForRow(0));
		jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTree1MousePressed(evt);
			}
		});
		jScrollPane2.setViewportView(jTree1);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154,
				Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234,
				Short.MAX_VALUE));

		jPanel9.setBackground(new java.awt.Color(0, 0, 0));
		jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jPanel9MouseEntered(evt);
			}
		});

		jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/gui/img/dropFiles.png"))); // NOI18N

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(
				jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 134,
				Short.MAX_VALUE));
		jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 122,
				Short.MAX_VALUE));

		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/gui/img/logo.jpg"))); // NOI18N

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanel3Layout
								.createSequentialGroup()
								.addGap(10, 10, 10)
								.addComponent(jPanel9,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(10, 10, 10))
				.addGroup(
						jPanel3Layout.createSequentialGroup()
								.addComponent(jLabel7).addContainerGap())
				.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
						154, Short.MAX_VALUE));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout
										.createSequentialGroup()
										.addComponent(jLabel7)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												234,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												60, Short.MAX_VALUE)
										.addComponent(
												jPanel9,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));

		jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

		jTable1.setBackground(new java.awt.Color(240, 240, 240));
		jTable1.setModel(model1);
		jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jTable1.setGridColor(new java.awt.Color(240, 240, 240));
		jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
		jTable1.setSelectionForeground(new java.awt.Color(240, 240, 240));
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTable1MousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 867,
				Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234,
				Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanel2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jToolBar1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																867,
																Short.MAX_VALUE)
														.addComponent(
																jPanel4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jPanel3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(15,
																				15,
																				15)
																		.addComponent(
																				jToolBar1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jPanel4,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jPanel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		jMenu1.setText("File");

		jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_T,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem1.setText("Add torrent file");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("Exit");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Options");

		jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_P,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem9.setText("Preference");
		jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem9ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem9);
		jMenu2.add(jSeparator5);

		jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_F4, 0));
		jMenuItem6.setText("Show ToolBar");
		jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem6ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem6);

		jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_F5, 0));
		jMenuItem7.setText("Show Detailed Info");
		jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem7ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem7);

		jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_F6, 0));
		jMenuItem8.setText("Show Category List");
		jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem8ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem8);

		jMenuBar1.add(jMenu2);

		jMenu3.setText("Help");
		jMenuBar1.add(jMenu3);

		setJMenuBar(jMenuBar1);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		showFileChooser();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		// TODO add your handling code here:
		showFileChooser();
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem9ActionPerformed
		// TODO add your handling code here:
		if (!preferenceFrame.isVisible()) {
			jTextField1.setText(directoryPath);
			if (OperatingSystem.windows()) {
				if (directoryPath.equalsIgnoreCase(System
						.getProperty("user.home") + "\\Downloads")) {
					jCheckBox1.setSelected(true);
					jTextField1.setEditable(false);
					jButton6.setEnabled(false);
				} else {
					jCheckBox1.setSelected(false);
					jTextField1.setEditable(true);
					jButton6.setEnabled(true);
				}
			} else if (OperatingSystem.mac()) {
				if (directoryPath.equalsIgnoreCase(System
						.getProperty("user.home") + "/Downloads")) {
					jCheckBox1.setSelected(true);
					jTextField1.setEditable(false);
					jButton6.setEnabled(false);
				} else {
					jCheckBox1.setSelected(false);
					jTextField1.setEditable(true);
					jButton6.setEnabled(true);
				}
			} else if (OperatingSystem.unix()) {
				if (directoryPath.equalsIgnoreCase(System
						.getProperty("user.home") + "/Downloads")) {
					jCheckBox1.setSelected(true);
					jTextField1.setEditable(false);
					jButton6.setEnabled(false);
				} else {
					jCheckBox1.setSelected(false);
					jTextField1.setEditable(true);
					jButton6.setEnabled(true);
				}
			}
			jTextField2.setText(Integer.toString(port));
			jTextField3.setText(Integer.toString(globalNumWant));
			jTextField4.setText(Integer.toString(numWant));
		}
		preferenceFrame.setSize(520, 420);
		Toolkit toolkit = Toolkit.getDefaultToolkit();
		Dimension dim = toolkit.getScreenSize();
		int x = (dim.width - preferenceFrame.getWidth()) / 2;
		int y = (dim.height - preferenceFrame.getHeight()) / 2;
		preferenceFrame.setLocation(x, y);
		preferenceFrame.setResizable(false);
		preferenceFrame.setAlwaysOnTop(true);
		preferenceFrame.setVisible(true);

	}// GEN-LAST:event_jMenuItem9ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
		if (jTable1.getSelectedRow() > -1) {
			System.out.println(receive.control.getId(jTable1.getSelectedRow()));
			receive.sendRemove(receive.control.getId(jTable1.getSelectedRow()));
		}
		int[] a;
		a = ErBit.jTable1.getSelectedRows();
		for (int i = a.length - 1; i > -1; i--) {
			receive.removeRow(model1, a[i]);
		}
		receive.removeList(model2);
		receive.removeList(model3);
		receive.removeList(model4);
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jTree2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTree2MousePressed
		// TODO add your handling code here:
		if (jTree2.getSelectionPath().toString()
				.compareTo("[Preference, General]") == 0) {
			jPanel8.setVisible(false);
			jPanel12.setVisible(false);
			jPanel7.setVisible(true);
		} else if (jTree2.getSelectionPath().toString()
				.compareTo("[Preference, UI Settings]") == 0) {
			jPanel7.setVisible(false);
			jPanel12.setVisible(false);
			jPanel8.setVisible(true);
		} else if (jTree2.getSelectionPath().toString()
				.compareTo("[Preference, Directories]") == 0) {
			jPanel7.setVisible(false);
			jPanel8.setVisible(false);
			jPanel12.setVisible(true);
		} else {
			jPanel8.setVisible(false);
			jPanel12.setVisible(false);
			jPanel7.setVisible(true);
		}
	}// GEN-LAST:event_jTree2MousePressed

	private void jCheckBox1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jCheckBox1MousePressed
		// TODO add your handling code here:
		if (!jCheckBox1.isSelected()) {
			jTextField1.setEditable(false);
			jButton6.setEnabled(false);
			String s = System.getProperty("user.home");
			if (OperatingSystem.windows()) {
				jTextField1.setText(s + "\\Downloads");
			} else if (OperatingSystem.mac()) {
				jTextField1.setText(s + "/Downloads");
			} else if (OperatingSystem.unix()) {
				jTextField1.setText(s + "/Downloads");
			}

		} else {
			jTextField1.setEditable(true);
			jButton6.setEnabled(true);
		}
	}// GEN-LAST:event_jCheckBox1MousePressed

	private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField1KeyPressed
		// TODO add your handling code here:
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			checkDirectory(jTextField1.getText());
		}
	}// GEN-LAST:event_jTextField1KeyPressed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
		// TODO add your handling code here:
		showFileChooser2();
	}// GEN-LAST:event_jButton6ActionPerformed

	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem6ActionPerformed
		// TODO add your handling code here:
		if (jToolBar1.isVisible()) {
			jToolBar1.setVisible(false);
		} else {
			jToolBar1.setVisible(true);
		}
	}// GEN-LAST:event_jMenuItem6ActionPerformed

	private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem7ActionPerformed
		// TODO add your handling code here:
		if (jPanel2.isVisible()) {
			jPanel2.setVisible(false);
		} else {
			jPanel2.setVisible(true);
		}
	}// GEN-LAST:event_jMenuItem7ActionPerformed

	private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem8ActionPerformed
		// TODO add your handling code here:
		if (jPanel3.isVisible()) {
			jPanel3.setVisible(false);
		} else {
			jPanel3.setVisible(true);
		}
	}// GEN-LAST:event_jMenuItem8ActionPerformed

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
		// TODO add your handling code here:
		System.exit(0);
	}// GEN-LAST:event_jMenuItem2ActionPerformed

	private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel9MouseEntered
		// TODO add your handling code here:
		// new FileDrop( jPanel9, /*dragBorder,*/ new FileDrop.Listener()
		// { @Override
		// public void filesDropped( java.io.File[] files ){
		// // { for( int i = 0; i < files.length; i++ )
		// /* {*/ try
		// { receive.sendPath( files[0].getCanonicalPath());
		// } // end try
		// catch( java.io.IOException e ) {System.out.println(e.getMessage());}
		// //} // end for: through each dropped file
		// //}
		// } // end filesDropped
		// }); // end FileDrop.Listener
	}// GEN-LAST:event_jPanel9MouseEntered

	private void jTree1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTree1MousePressed
		// TODO add your handling code here:
		int row[] = ErBit.jTable1.getSelectedRows();
		for (int a = 0; a < row.length; a++) {
			jTable1.removeRowSelectionInterval(row[a], row[a]);
		}

		receive.updateTree();
		receive.removeList(model2);
		receive.removeList(model3);
		receive.removeList(model4);
	}// GEN-LAST:event_jTree1MousePressed

	private void jTable1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MousePressed
		// TODO add your handling code here:
		receive.updateList(jTable1.getSelectedRow());
	}// GEN-LAST:event_jTable1MousePressed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		if (jTable1.getSelectedRow() > -1) {
			System.out.println(receive.control.getId(jTable1.getSelectedRow()));
			receive.sendPause(receive.control.getId(jTable1.getSelectedRow()));
		}
		// wb.webBrowserVisible();

	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		// TODO add your handling code here:
		if (jTable1.getSelectedRow() > -1) {
			System.out.println(receive.control.getId(jTable1.getSelectedRow()));
			receive.sendStart(receive.control.getId(jTable1.getSelectedRow()));
		}
	}// GEN-LAST:event_jButton5ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		if (jTable1.getSelectedRow() > -1) {
			System.out.println(receive.control.getId(jTable1.getSelectedRow()));
			receive.sendStop(receive.control.getId(jTable1.getSelectedRow()));
		}
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
		// TODO add your handling code here:

		if (checkDirectory(jTextField1.getText())) {
			try {
				port = Integer.parseInt(jTextField2.getText());
				globalNumWant = Integer.parseInt(jTextField3.getText());
				numWant = Integer.parseInt(jTextField4.getText());
				System.out.println("Det blev inga problem");
				JOptionPane.showMessageDialog(preferenceFrame, "Applied");

			} catch (Exception e) {
				System.out.println("Exception: " + e.getMessage());
				Toolkit.getDefaultToolkit().beep();
				JOptionPane.showMessageDialog(preferenceFrame,
						"Wrong input, you have to input numbers only (0-9)");
			}
		}
	}// GEN-LAST:event_jButton7ActionPerformed

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
		// TODO add your handling code here:
		int i = JOptionPane.showConfirmDialog(preferenceFrame,
				"Are you sure you want to cancel?", "Confirmation", 0);
		if (i == 0) {
			preferenceFrame.setVisible(false);
			jTextField1.setText(directoryPath);
			jTextField2.setText(Integer.toString(port));
			jTextField3.setText(Integer.toString(globalNumWant));
			jTextField4.setText(Integer.toString(numWant));
		} else if (i == 1) {

		} else if (i == -1) {

		}

	}// GEN-LAST:event_jButton8ActionPerformed

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton9ActionPerformed
		// TODO add your handling code here:
		if (checkDirectory(jTextField1.getText())) {
			try {
				port = Integer.parseInt(jTextField2.getText());
				globalNumWant = Integer.parseInt(jTextField3.getText());
				numWant = Integer.parseInt(jTextField4.getText());
				System.out.println("Det blev inga problem");
				preferenceFrame.setVisible(false);

			} catch (Exception e) {
				System.out.println("Exception: " + e.getMessage());
				Toolkit.getDefaultToolkit().beep();
				JOptionPane.showMessageDialog(preferenceFrame,
						"Wrong input, you have to input numbers only (0-9)");
			}
		}
	}// GEN-LAST:event_jButton9ActionPerformed

	private boolean checkDirectory(String s) {
		File f = new File(s);
		try {
			if (f.mkdirs()) {
				jTextField1.setText(s);
				directoryPath = s;
				System.out.println("Den skapas");
				return true;
			} else if (f.exists()) {
				jTextField1.setText(s);
				directoryPath = s;
				System.out.println("Den finns");
				return true;
			} else {
				Toolkit.getDefaultToolkit().beep();
				JOptionPane
						.showMessageDialog(preferenceFrame,
								"The path you selected is wrong, please reselect path.");
				return false;
			}
		} catch (Exception e) {
			e.printStackTrace();
			return false;
		}
	}

	private void showFileChooser() {
		JfileFrame.setAlwaysOnTop(true);
		JfileFrame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
		fileChooser = new JFileChooser(".");
		JfileFrame.add(fileChooser, BorderLayout.CENTER);

		FileNameExtensionFilter filter = new FileNameExtensionFilter("torrent",
				"torrent");
		fileChooser.setFileFilter(filter);

		// Create ActionListener
		ActionListener actionListener = new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				JFileChooser theFileChooser = (JFileChooser) actionEvent
						.getSource();
				String command = actionEvent.getActionCommand();
				if (command.equals(JFileChooser.APPROVE_SELECTION)) {
					File selectedFile = theFileChooser.getSelectedFile();
					String directory = selectedFile.getParent();
					String fileName = selectedFile.getName();
					String completeName = directory + "\\" + fileName;
					receive.sendPath(completeName, directoryPath, numWant,
							globalNumWant, port);
					JfileFrame.setVisible(false);
				} else if (command.equals(JFileChooser.CANCEL_SELECTION)) {
					JfileFrame.setVisible(false);
				}
			}
		};
		fileChooser.addActionListener(actionListener);
		JfileFrame.pack();
		Toolkit toolkit = Toolkit.getDefaultToolkit();
		Dimension dim = toolkit.getScreenSize();
		int x = (dim.width - JfileFrame.getWidth()) / 2;
		int y = (dim.height - JfileFrame.getHeight()) / 2;
		JfileFrame.setLocation(x, y);
		JfileFrame.setVisible(true);
	}

	private void fileDrop() {
		new FileDrop(jPanel9, /* dragBorder, */new FileDrop.Listener() {
			@Override
			public void filesDropped(java.io.File[] files) {

				// { for( int i = 0; i < files.length; i++ )
				/* { */try {
					receive.sendPath(files[0].getCanonicalPath(),
							directoryPath, numWant, globalNumWant, port);
				} // end try
				catch (java.io.IOException e) {
					System.out.println(e.getMessage());
				}
				// } // end for: through each dropped file
				// }
			} // end filesDropped
		}); // end FileDrop.Listener
	}

	private void showFileChooser2() {

		JfileFrame2.setAlwaysOnTop(true);
		JfileFrame2.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
		fileChooser2 = new JFileChooser(".");
		fileChooser2.addChoosableFileFilter(null);
		JfileFrame2.add(fileChooser2, BorderLayout.CENTER);
		fileChooser2.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

		// Create ActionListener
		ActionListener actionListener = new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				JFileChooser theFileChooser = (JFileChooser) actionEvent
						.getSource();
				String command = actionEvent.getActionCommand();
				if (command.equals(JFileChooser.APPROVE_SELECTION)) {
					File selectedFile = theFileChooser.getSelectedFile();
					String folder = selectedFile.getPath();
					jTextField1.setText(folder);
					JfileFrame2.setVisible(false);
				} else if (command.equals(JFileChooser.CANCEL_SELECTION)) {
					JfileFrame2.setVisible(false);
				}
			}
		};
		fileChooser2.addActionListener(actionListener);
		JfileFrame2.pack();
		Toolkit toolkit = Toolkit.getDefaultToolkit();
		Dimension dim = toolkit.getScreenSize();
		int x = (dim.width - JfileFrame2.getWidth()) / 2;
		int y = (dim.height - JfileFrame2.getHeight()) / 2;
		JfileFrame2.setLocation(x, y);
		JfileFrame2.setVisible(true);

	}

	private void receiveMessages() {
		while (true) {
			receive.receiveMessages();
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				System.out.println(info.getName());
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				} else if ("GTK+".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}

		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ErBit.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ErBit.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ErBit.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ErBit.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		new ErBit();

	}

	private static Object rowData1[][];
	private static Object columnNames1[] = { "Nr", "Filename", "Size",
			"Status", "Download Speed", "Upload Speed", "Seeders", "Leechers",
			"Downloaded", "Uploaded" };
	public static DefaultTableModel model1 = new DefaultTableModel(rowData1,
			columnNames1);
	private static Object rowData2[][];
	private static Object columnNames2[] = { "IP", "Port" };
	public static DefaultTableModel model2 = new DefaultTableModel(rowData2,
			columnNames2);
	private static Object rowData3[][];
	private static Object columnNames3[] = { "Name" };
	public static DefaultTableModel model3 = new DefaultTableModel(rowData3,
			columnNames3);
	private static Object rowData4[][];
	private static Object columnNames4[] = { "Filename" };
	public static DefaultTableModel model4 = new DefaultTableModel(rowData4,
			columnNames4);
	private int numWant = 50;
	private int globalNumWant = 200;
	private int port = 3333;
	private String directoryPath = System.getProperty("user.home");
	private javax.swing.JFrame JfileFrame = new JFrame("JFileChooser Popup");
	private javax.swing.JFrame JfileFrame2 = new JFrame("JFileChooser Popup");
	private javax.swing.JFileChooser fileChooser;
	private javax.swing.JFileChooser fileChooser2;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private javax.swing.JMenuItem jMenuItem9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	public static javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	public static javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JToolBar.Separator jSeparator1;
	private javax.swing.JToolBar.Separator jSeparator2;
	private javax.swing.JToolBar.Separator jSeparator3;
	private javax.swing.JToolBar.Separator jSeparator4;
	private javax.swing.JPopupMenu.Separator jSeparator5;
	private javax.swing.JTabbedPane jTabbedPane1;
	public static javax.swing.JTable jTable1;
	public static javax.swing.JTable jTable2;
	public static javax.swing.JTable jTable3;
	public static javax.swing.JTable jTable4;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JToolBar jToolBar1;
	public static javax.swing.JTree jTree1;
	private javax.swing.JTree jTree2;
	private javax.swing.JFrame preferenceFrame;
	// End of variables declaration//GEN-END:variables
}
